---
name: Net-OBEX
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: implementation of OBEX protocol
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  IO::Handle: 1.27
  Net::OBEX::Packet::Headers: 0.002
  Net::OBEX::Packet::Request: 0.003
  Net::OBEX::Response: 0.002
  Socket::Class: 1.13
build_requires:
  Test::More: 0
provides:
  Net::OBEX:
    file: lib/Net/OBEX.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
