---
abstract: 'implementation of OBEX protocol'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OBEX
provides:
  Net::OBEX:
    file: lib/Net/OBEX.pm
    version: 0.006
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  Devel::TakeHashArgs: 0.002
  IO::Handle: 1.27
  Net::OBEX::Packet::Headers: 0.002
  Net::OBEX::Packet::Request: 0.003
  Net::OBEX::Response: 0.002
  Socket::Class: 1.13
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.006
