---
name: Net-OBEX
version: 0.005
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: implementation of OBEX protocol
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  Devel::TakeHashArgs: 0.002
  IO::Handle: 1.27
  Net::OBEX::Packet::Headers: 0.002
  Net::OBEX::Packet::Request: 0.003
  Net::OBEX::Response: 0.002
  Socket::Class: 1.13
configure_requires:
  Module::Build: 0.34
provides:
  Net::OBEX:
    file: lib/Net/OBEX.pm
    version: 0.005
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
